### ISSUE TITLE
Add config file to enter game location

### ISSUE THREAD

**Issue by PureTryOut** [danhedron/openrw#23]
At this moment you have to export the OPENRW_GAME_PATH variable to get your game to run. It would be preferable to have a config file (say ~/.config/openrw/config) to specify the location of the game. This would allow .desktop files to run the game, as you don't have to export the variable every time anymore.

**Comment by danhedron** [comment]
2ee4a6e5339798df7eadd1d81d1e7d21885a4a6d adds this.
