### ISSUE TITLE
Minimap goes out of it's window (NVIDIA proprietary drivers 364.19)

### ISSUE THREAD

**Issue by PureTryOut** [danhedron/openrw#25]
Using the NVIDIA proprietary drivers 364.19 on Arch Linux causes the minimap to go out of it's window. This is not reproducable on Mesa.

![untitled window_003](https://cloud.githubusercontent.com/assets/1565836/15410733/b131835a-1e1b-11e6-877e-357c5d861a6c.png)

**Comment by TacoDeBoss** [comment]
![screenshot_2016-05-20_05-54-33](https://cloud.githubusercontent.com/assets/2870898/15428328/87fc94dc-1e4f-11e6-99b7-b67be1ee827d.png)

Not reproducable on AMD fglrx drivers. (15.3)

**Comment by TacoDeBoss** [comment]
Map working as expected on fglrx 15.3.
![screenshot_2016-05-20_05-54-33](https://cloud.githubusercontent.com/assets/2870898/15428417/14378808-1e50-11e6-9f5f-3f73186f934a.png)

**Comment by TacoDeBoss** [comment]
Reproduced on Nvidia 361.42 with a GTX 770.
![screenshot_2016-05-20_11-28-04](https://cloud.githubusercontent.com/assets/2870898/15436224/03928268-1e7e-11e6-87b4-9ecc2b100af6.png)

**Comment by cmol** [comment]
I have the same issue on a Nvidia GTX 970 with driver 352.63.

**Comment by danhedron** [comment]
Can anyone affected by this see if it's fixed by 46961f8

**Comment by PureTryOut** [comment]
Fixed! That was a small fix, thanks!
