### ISSUE TITLE
Several graphical glitches on proprietary NVIDIA drivers

### ISSUE THREAD

**Issue by PureTryOut** [danhedron/openrw#26]
Arch Linux, proprietary NVIDIA drivers 364.19.
The game is red, and the sky is sort of green/blueish.
After a while of running around the graphics start glitching around and colliding with each other.

![untitled window_003](https://cloud.githubusercontent.com/assets/1565836/15411084/cf924f62-1e1d-11e6-86d9-d8ea317a756d.png)

(ignore the minimap out of it's window, that is reported at #25 already)

**Comment by TacoDeBoss** [comment]
@PureTryOut Finally got back to my desktop. Coloring issue is not present on GTX 780 Ti running 367.18 drivers.

**Comment by PureTryOut** [comment]
Strange, GTX980 here.

When the game boots it's either rendering like above, or displaying just one (seemingly random) solid color. I have to restart the game a few times to get it playable like above again.

**Comment by tsjost** [comment]
Uninitialized data, ahoy. Seem to have affected some Intel Mesas as well.

**Comment by tjbp** [comment]
It's improved to the point where I can actually see Fido now, but still have similar problems:

![screenshot_20160523_191253](https://cloud.githubusercontent.com/assets/2157634/15479956/c7dd8afc-211a-11e6-9089-b14551624bbb.png)

**Comment by tsjost** [comment]
@tjbp: Weird. Have you actually checked out the latest changes on master and done a clean new build?

**Comment by PureTryOut** [comment]
Yeah he also has the minimap bug still. Looks like a not properly updated build to me.

**Comment by tjbp** [comment]
Yep, my bad, hadn't realised my package manager was caching the source.
