### ISSUE TITLE
Assertion `x >= genType(0)' failed

### ISSUE THREAD

**Issue by neuromancer** [danhedron/openrw#35]
You can trigger an assertion fail if you start the game and press enter during the cutscene. I got this backtrace:

    Starting program: /home/g/Games/openrw/rwgame/rwgame 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff094a700 (LWP 6711)]
    I [Game] Game directory: /home/g/Games/GTA3
    Max UBO Size: 16384
    UBO Alignment: 16
    Max batch size: 128
    I [Renderer] OpenGL Renderer Version: 3.0 Mesa 10.1.3 (GLSL 1.30) Vendor: Intel Open Source     Technology Center
    [New Thread 0x7fffe8dc2700 (LWP 6714)]
    [Thread 0x7fffe8dc2700 (LWP 6714) exited]
    [New Thread 0x7fffe8dc2700 (LWP 6715)]
    [New Thread 0x7fffdffff700 (LWP 6716)]
    I [Data] Loaded 42 zones from /home/g/Games/GTA3/data/gta3.zon
    I [Game] Started
    Failed to open sound file "/home/g/Games/GTA3/audio/City.wav" (System error : No such file or directory.)
    I [World] Loaded cutscene: BET
    [New Thread 0x7fffd742d700 (LWP 6744)]
    [Thread 0x7fffd742d700 (LWP 6744) exited]
    libmad error: lost synchronizationlibmad error: lost synchronizaI [World] Loaded cutscene: JB
    [New Thread 0x7fffd742d700 (LWP 6748)]
    I [World] Creating Vehicle ID 116 (POLICAR)
    I [World] Creating Vehicle ID 117 (ENFORCR)
    I [World] Creating Vehicle ID 130 (RUMPO)
    I [World] Creating Vehicle ID 96 (PATRIOT)
    I [World] Creating Vehicle ID 110 (TAXI)
    I [World] Creating Vehicle ID 105 (CHEETAH)
    I [World] Creating Vehicle ID 92 (STINGER)
    I [World] Creating Vehicle ID 105 (CHEETAH)
    I [World] Creating Vehicle ID 92 (STINGER)
    I [World] Creating Vehicle ID 111 (KURUMA)
    I [World] Creating Vehicle ID 110 (TAXI)
    I [World] Creating Vehicle ID 111 (KURUMA)
    I [World] Creating Vehicle ID 110 (TAXI)
    rwgame: /usr/include/glm/detail/func_exponential.inl:149: genType glm::sqrt(const genType&)     [with genType = float]: Assertion `x >= genType(0)' failed.

    Program received signal SIGABRT, Aborted.
    0x00007ffff59a7cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff59a7cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007ffff59ab0d8 in __GI_abort () at abort.c:89
    #2  0x00007ffff59a0b86 in __assert_fail_base (fmt=0x7ffff5af1830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
        assertion=assertion@entry=0x69cb75 "x >= genType(0)", file=file@entry=0x69cb48 "/usr/include/glm/detail/func_exponential.inl", 
        line=line@entry=149, 
        function=function@entry=0x69cec0 <float glm::sqrt<float>(float const&)::__PRETTY_FUNCTION__> "genType glm::sqrt(const genType&) [with genType = float]") at assert.c:92
    #3  0x00007ffff59a0c32 in __GI___assert_fail (assertion=0x69cb75 "x >= genType(0)", file=0x69cb48 "/usr/include/glm/detail/func_exponential.inl", 
        line=149, 
        function=0x69cec0 <float glm::sqrt<float>(float const&)::__PRETTY_FUNCTION__> "genType glm::sqrt(const genType&) [with genType = float]")
        at assert.c:101
    #4  0x0000000000581bfa in float glm::sqrt<float>(float const&) ()
    #5  0x000000000058fbb2 in float glm::length<float, (glm::precision)0>(glm::detail::tvec3<float,    (glm::precision)0> const&) ()
    #6  0x00000000005e06e5 in renderGeometry(GameWorld*, Model*, unsigned long, glm::detail::tmat4x4<float, (glm::precision)0> const&, float, GameObject*, ViewCamera const&, std::vector<Renderer::RenderInstruction, std::allocator<Renderer::RenderInstruction> >&) ()
    #7  0x00000000005e1b3c in renderWheel(GameWorld*, VehicleObject*, Model*, glm::detail::tmat4x4<float, (glm::precision)0> const&, std::string const&, ViewCamera const&, std::vector<Renderer::RenderInstruction, std::allocator<Renderer::RenderInstruction> >&) ()
    #8  0x00000000005e22cb in renderVehicle(GameWorld*, VehicleObject*, ViewCamera const&, float, std::vector<Renderer::RenderInstruction, std::allocator<Renderer::RenderInstruction> >&) ()
    #9  0x00000000005e30bd in ObjectRenderer::buildRenderList(GameWorld*, GameObject*, ViewCamera const&, float, std::vector<Renderer::RenderInstruction, std::allocator<Renderer::RenderInstruction> >&) ()
    #10 0x00000000005cc843 in GameRenderer::renderWorld(GameWorld*, ViewCamera const&, float) ()
    #11 0x000000000057d3e2 in RWGame::render(float, float) ()
    #12 0x000000000057c380 in RWGame::run() ()
    #13 0x00000000005779e2 in main ()

**Comment by danhedron** [comment]
1a2a381 Fixes this. Can you confirm it fixes it for you?

**Comment by neuromancer** [comment]
> Fixes this. Can you confirm it fixes it for you?

Yes. Thanks!
