### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by cmol** [danhedron/openrw#37]
Hi

After building and installing the game, running results in:

    Warning: The created OpenGL context does not fully meet the settings that were requested
    Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false
    Created: version = 4.5 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false
    I [Game] Game directory: /tank/storage/GTA3/
    Max UBO Size: 65536
    UBO Alignment: 256
    Max batch size: 512
    I [Renderer] OpenGL Renderer Version: 4.5.0 NVIDIA 352.63 (GLSL 4.50 NVIDIA) Vendor: NVIDIA Corporation
    I [Data] Loaded 42 zones from /tank/storage/GTA3//data/gta3.zon
    I [Game] Started
    [1]    11543 segmentation fault (core dumped)  rwgame

**Comment by danhedron** [comment]
Can you get a back trace from gdb? I haven't seen a crash like this before.

**Comment by cmol** [comment]
Sure :)

```
Starting program: /home/cmol/src/openrw/build/rwgame/rwgame 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffefa43700 (LWP 12350)]
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false
Created: version = 4.5 ; depth bits = 24 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false
I [Game] Game directory: /tank/storage/GTA3/
Max UBO Size: 65536
UBO Alignment: 256
Max batch size: 512
I [Renderer] OpenGL Renderer Version: 4.5.0 NVIDIA 352.63 (GLSL 4.50 NVIDIA) Vendor: NVIDIA Corporation
[New Thread 0x7fffeccba700 (LWP 12351)]
[Thread 0x7fffeccba700 (LWP 12351) exited]
[New Thread 0x7fffeccba700 (LWP 12352)]
[New Thread 0x7fffec4b9700 (LWP 12353)]
I [Data] Loaded 42 zones from /tank/storage/GTA3//data/gta3.zon
I [Game] Started

Program received signal SIGSEGV, Segmentation fault.
0x00000000004a97a5 in WaterRenderer::render(GameRenderer*, GameWorld*) ()
```

I'm not that good at debugging with gdb (yet), but tell me what you want done and I'll try!

**Comment by danhedron** [comment]
In the gdb prompt, you can type "bt" to print the back trace for the current thread.

Looks like it could be the water texture is missing, can you try 8e629fd and see if that fixes the crash? (or makes it crash elsewhere).

**Comment by cmol** [comment]
Back trace is:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004a97a5 in WaterRenderer::render(GameRenderer*, GameWorld*) ()
(gdb) bt
#0  0x00000000004a97a5 in WaterRenderer::render(GameRenderer*, GameWorld*) ()
#1  0x00000000004c2249 in GameRenderer::renderWorld(GameWorld*, ViewCamera const&, float) ()
#2  0x000000000044838a in RWGame::render(float, float) ()
#3  0x00000000004492ce in RWGame::run() ()
#4  0x000000000043cf40 in main ()
```

When I apply the patch I get:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004d6838 in TextRenderer::renderText(TextRenderer::TextInfo const&) ()
(gdb) bt
#0  0x00000000004d6838 in TextRenderer::renderText(TextRenderer::TextInfo const&) ()
#1  0x000000000044e38a in LoadingState::draw(GameRenderer*) ()
#2  0x0000000000449a04 in RWGame::run() ()
#3  0x000000000043cf40 in main ()
```

If it's the game file I should try to find another copy of the game. The one I'm using is from an old windows partition from long long time ago.

**Comment by danhedron** [comment]
Another copy of the data might give you more success, I and others have used the data from Steam. It would be nice to know why it isn't working with your data, can you provide a bit more detail so this can be investigated in future?

* What file system is the game on (NTFS?)
* Is the data retail or from steam?

**Comment by cmol** [comment]
It's an old retail game and I have it on a zfs partition. How do you get the data files installed via the steam version? Using wine? :)

**Comment by TacoDeBoss** [comment]
You can use the tool called SteamCMD if you like. You can use it to download Windows games on Linux. It's not too difficult.

**Comment by cmol** [comment]
@TacoDeBoss, are you using the windows or linux version of steamcmd?

**Comment by TacoDeBoss** [comment]
@cmol I'm using the Linux version. You can use a command in SteamCMD to force the platform so you can download Windows games.

**Comment by cmol** [comment]
Much more success now. The game starts up and runs the first cutscene (in which it crashes like in #27).

Thanks for the help so far :) It's a fun project!
