### ISSUE TITLE
I can't enter cars 

### ISSUE THREAD

**Issue by neuromancer** [danhedron/openrw#38]
Using enter key, i can't enter cars. Nothing happens. I also noticed that i can walk though cars, but i'm not sure this is related.

**Comment by danhedron** [comment]
The enter vehicle key is currently F. There's no imput map system in place yet to support re-mapping this to Enter, but it will be needed to populate the help hints with the appropriate key.

**Comment by neuromancer** [comment]
Thanks!. Should i create another issue report for the lack of collision when walking? (everything seems fine when i'm driving a car)

**Comment by danhedron** [comment]
That's a known issue. The pedestrian collision system will be replaced soon anyway so that should be fixed when that happens.
