### ISSUE TITLE
Make fails with 'Could not find a package configuration file provided by "GLM"'

### ISSUE THREAD

**Issue by TacoDeBoss** [danhedron/openrw#41]
As of this hour, compilation now fails on my Linux system, something relating to GLM. libglm-dev is installed, but `make` results in

-- Found SFML 2.1.0 in /usr/include
-- Found MAD in /usr/include
CMake Error at CMakeLists.txt:61 (find_package):
  By not providing "FindGLM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GLM", but
  CMake did not find one.

  Could not find a package configuration file provided by "GLM" with any of
  the following names:

    GLMConfig.cmake
    glm-config.cmake

  Add the installation prefix of "GLM" to CMAKE_PREFIX_PATH or set "GLM_DIR"
  to a directory containing one of the above files.  If "GLM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/taco/stuff/openrw-git/openrw/build/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] Error 1

**Comment by danhedron** [comment]
Looks like FindGLM was deprecated and replaced by the new packaging system that I'm not familiar with in https://github.com/g-truc/glm/commit/62a7daddcf082f754000fc5e42d7bcdf93c895f7

**Comment by TacoDeBoss** [comment]
I fixed it by copying a FindGLM.cmake into the /cmake/modules folder.
I found the FindGLM.cmake at https://github.com/lighttransport/nanogi/blob/master/cmake/FindGLM.cmake
So I'm good, but what about others having this problem?

**Comment by TacoDeBoss** [comment]
From the terminal output before FindGLM.cmake was placed
`Add the installation prefix of "GLM" to CMAKE_PREFIX_PATH or set "GLM_DIR"
  to a directory containing one of the above files.  If "GLM" provides a
  separate development package or SDK, be sure it has been installed`
I'm honestly not a programmer, but if we can direct whatever cmake file to /usr/include/glm as the GLM directory, it would replace the need for the FindGLM file, yes?
Apologies for not being able to help to a greater degree.

**Comment by neuromancer** [comment]
> So I'm good, but what about others having this problem?

I had the same problem. Your workaround solved it.
