### ISSUE TITLE
Cmake still fails with GLM errors

### ISSUE THREAD

**Issue by TacoDeBoss** [danhedron/openrw#44]
GLM is installed but `cmake ../ -DCMAKE_BUILD_TYPE=Release` fails with the following:

-- Found SFML 2.3.2 in /usr/include
-- Found MAD in /usr/include
CMake Error at /usr/lib/cmake/glm/glmConfig.cmake:10 (message):
  File or directory //include referenced by variable GLM_INCLUDE_DIRS does
  not exist !
Call Stack (most recent call first):
  /usr/lib/cmake/glm/glmConfig.cmake:16 (set_and_check)
  CMakeLists.txt:61 (find_package)

-- Configuring incomplete, errors occurred!

#43 seems to have caused this issue.

**Comment by TacoDeBoss** [comment]
Reverting changes made in #43 and using changes proposed in #42 fixes the issue.

**Comment by TacoDeBoss** [comment]
It seems after the initial cmake command produced in my modified copy with my fix, a regular copy of the code compiles fine.

**Comment by danhedron** [comment]
Downloading and installing the latest version of GLM from https://github.com/g-truc/glm should resolve this for you.

**Comment by TacoDeBoss** [comment]
@danhedron Seeing as the problem doesn't seem to happen anymore, I'll close the issue. Thank you!
